/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LostRouteImport } from './routes/lost'
import { Route as FoundRouteImport } from './routes/found'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const LostRoute = LostRouteImport.update({
  id: '/lost',
  path: '/lost',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundRoute = FoundRouteImport.update({
  id: '/found',
  path: '/found',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/found': typeof FoundRoute
  '/lost': typeof LostRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/found': typeof FoundRoute
  '/lost': typeof LostRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/found': typeof FoundRoute
  '/lost': typeof LostRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/found' | '/lost'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/found' | '/lost'
  id: '__root__' | '/' | '/auth' | '/found' | '/lost'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FoundRoute: typeof FoundRoute
  LostRoute: typeof LostRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lost': {
      id: '/lost'
      path: '/lost'
      fullPath: '/lost'
      preLoaderRoute: typeof LostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/found': {
      id: '/found'
      path: '/found'
      fullPath: '/found'
      preLoaderRoute: typeof FoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FoundRoute: FoundRoute,
  LostRoute: LostRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
